# Run python3 setup.py install --user

# Generated by CodiumAI

import pytest
from aimon_rely_client.simple_client import SimpleAimonRelyClient, RetryableError, Config

API_KEY = "YOUR API KEY HERE"
class TestSimpleAimonRelyClient:

    #  Sends an HTTP POST request to the Aimon Rely Hallucination Detection API with valid data and receives a valid response
    def test_valid_data_valid_response(self):
        config = Config({'hallucination': 'default'})
        client = SimpleAimonRelyClient(api_key=API_KEY, config=config)
        data_to_send = [{"context": "This is the context", "generated_text": "This is the context"}]
        response = client.detect(data_to_send)
        assert "hallucination" in response
        assert "is_hallucinated" in response['hallucination']
        assert response['hallucination']["is_hallucinated"] == "False"
        assert "score" in response['hallucination']
        assert "sentences" in response['hallucination']
        assert len(response['hallucination']["sentences"]) == 1

    #  Sends an HTTP POST request to the Aimon Rely Hallucination Detection API with a single dict object containing a valid "context" and "generated_text" but with a very short text and receives a valid response
    def test_short_text_valid_response(self):
        config = Config({'hallucination': 'default'})
        client = SimpleAimonRelyClient(api_key=API_KEY, config=config)
        short_text = "a"
        data_to_send = [{"context": "This is the context", "generated_text": short_text}]
        response = client.detect(data_to_send)
        assert "hallucination" in response
        assert "is_hallucinated" in response['hallucination']
        assert response['hallucination']["is_hallucinated"] == "True"
        assert "score" in response['hallucination']
        assert "sentences" in response['hallucination']
        assert len(response['hallucination']["sentences"]) == 1

    #  Sends an HTTP POST request to the Aimon Rely Hallucination Detection API with a single dict object containing a valid "context" and "generated_text" but with a text containing special characters and receives a valid response
    def test_special_characters_valid_response(self):
        client = SimpleAimonRelyClient(api_key=API_KEY)
        special_text = "!@#$%^&*()_+"
        data_to_send = [{"context": "This is the context", "generated_text": special_text}]
        response = client.detect(data_to_send)
        assert "hallucination" in response
        assert "is_hallucinated" in response['hallucination']
        assert response['hallucination']["is_hallucinated"] == "True"
        assert "score" in response['hallucination']
        assert "sentences" in response['hallucination']
        assert len(response['hallucination']["sentences"]) == 12

    def test_valid_data_valid_response_conciseness(self):
        config = Config({'conciseness': 'default'})
        client = SimpleAimonRelyClient(api_key=API_KEY, config=config)
        data_to_send = [{
                            "context": "the abc have reported that those who receive centrelink payments made up half of radio rental's income last year. Centrelink payments themselves were up 20%.",
                            "generated_text": "those who receive centrelink payments made up half of radio rental's income last year. The Centrelink payments were 20% up."}]
        response = client.detect(data_to_send)
        print(response["quality_metrics"])
        assert "quality_metrics" in response
        assert "results" in response["quality_metrics"]
        assert "conciseness" in response["quality_metrics"]["results"]
        assert "reasoning" in response["quality_metrics"]["results"]["conciseness"]
        assert "score" in response["quality_metrics"]["results"]["conciseness"]
        assert response["quality_metrics"]["results"]["conciseness"]["score"] >= 0.7

    def test_valid_data_valid_response_completeness(self):
        config = Config({'completeness': 'default'})
        client = SimpleAimonRelyClient(api_key=API_KEY, config=config)
        data_to_send = [{
                            "context": "the abc have reported that those who receive centrelink payments made up half of radio rental's income last year. Centrelink payments themselves were up 20%.",
                            "generated_text": "those who receive centrelink payments made up half of radio rental's income last year. The Centrelink payments were 20% up."}]
        response = client.detect(data_to_send)
        assert "quality_metrics" in response
        print(response["quality_metrics"])
        assert "results" in response["quality_metrics"]
        assert "completeness" in response["quality_metrics"]["results"]
        assert "reasoning" in response["quality_metrics"]["results"]["completeness"]
        assert "score" in response["quality_metrics"]["results"]["completeness"]
        assert response["quality_metrics"]["results"]["completeness"]["score"] > 0.7

    def test_valid_data_valid_response_conciseness_completeness(self):
        config = Config({'conciseness': 'default', 'completeness': 'default'})
        client = SimpleAimonRelyClient(api_key=API_KEY, config=config)
        data_to_send = [{"context": "the abc have reported that those who receive centrelink payments made up half of radio rental's income last year. Centrelink payments themselves were up 20%.",
                         "generated_text": "those who receive centrelink payments made up half of radio rental's income last year. The Centrelink payments were 20% up."}]
        response = client.detect(data_to_send)
        assert "quality_metrics" in response
        print(response["quality_metrics"])
        assert "results" in response["quality_metrics"]
        assert "completeness" in response["quality_metrics"]["results"]
        assert "reasoning" in response["quality_metrics"]["results"]["completeness"]
        assert "score" in response["quality_metrics"]["results"]["completeness"]
        assert response["quality_metrics"]["results"]["completeness"]["score"] > 0.7
        assert "quality_metrics" in response
        assert "results" in response["quality_metrics"]
        assert "conciseness" in response["quality_metrics"]["results"]
        assert "reasoning" in response["quality_metrics"]["results"]["conciseness"]
        assert "score" in response["quality_metrics"]["results"]["conciseness"]
        assert response["quality_metrics"]["results"]["conciseness"]["score"] > 0.7
