name: Publish Python Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*

      - name: Extract Release Notes
        id: release_notes
        run: |
          VERSION=$(python setup.py --version)
          RELEASE_NOTES=$(awk '/## \[${VERSION}\]/,/^## /' CHANGELOG.md | sed '$d')
          echo "::set-output name=notes::$RELEASE_NOTES"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.release_notes.outputs.version }}"
          release_name: "v${{ steps.release_notes.outputs.version }}"
          body: "${{ steps.release_notes.outputs.notes }}"
          draft: false
          prerelease: false
