name: Test on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest

      - name: Run tests
        env:
          AIMON_API_KEY: ${{ secrets.AIMON_API_KEY }}
        run: |

          ## Run only two test files
          # pytest tests/test_detect.py tests/test_evaluate.py

          ## Ignore some files and run without descriptive logging
          # pytest tests/ --ignore=tests/obsolete/ --ignore=tests/test_low_level_api.py -v

          ## Ignore some files and run with descriptive logging
          pytest tests/ --ignore=tests/obsolete/ --ignore=tests/test_low_level_api.py -v --log-cli-level=INFO
